/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    I18nExample: typeof import('./src/components/I18nExample.vue')['default']
    LocaleSwitcher: typeof import('./src/components/LocaleSwitcher.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
  }
}
